export type ToolCategory = 'interior_ai' | 'super_ai' | 'toolbox' | 'human';

export interface ParamOption {
  label: string;
  value: string;
}

export interface ToolParam {
  key: string;
  label: string;
  type: 'select' | 'slider' | 'text' | 'toggle';
  options?: ParamOption[];
  min?: number;
  max?: number;
  step?: number;
  defaultValue: string | number | boolean;
}

export interface ToolConfig {
  id: number;
  slug: string;
  title: string;
  featureKey: string;
  category: ToolCategory;
  image: string;
  /** 是否需要上传图片，默认 true；文生图工具为 false */
  requiresImage?: boolean;
  uploadLabel: string;
  uploadHint: string;
  hasPrompt: boolean;
  promptPlaceholder?: string;
  hasResolution: boolean;
  hasAspectRatio: boolean;
  hasDualImage: boolean;
  dualImageLabel?: string;
  /** 双图工具是否强制要求第二张图，默认 true；collage-render 为 false（第二张可选） */
  requiresSecondImage?: boolean;
  hasRoomSelect: boolean;
  hasRegion: boolean;
  regionHint?: string;
  customParams: ToolParam[];
  costPerGeneration: number;
  outputType: 'image' | 'text' | 'mixed';
}

export type EngineTypeKey =
  | 'gemini_direct'
  | 'vertex'
  | 'venice'
  | 'newapi'
  | 'swiftask'
  | string;

const UNSPLASH = (id: string) =>
  `https://images.unsplash.com/${id}?q=80&w=500&auto=format&fit=crop`;

export const toolConfigs: ToolConfig[] = [
  {
    id: 1,
    slug: 'sketch-render',
    title: '草图大师方案渲染',
    featureKey: 'sketch-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1517581177682-a085bb7ffb15'),
    uploadLabel: '上传草图大师方案',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的渲染效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 2,
    slug: 'banana-render',
    title: 'Nano Banana 香蕉模型渲染',
    featureKey: 'banana-pro-edit',
    category: 'super_ai',
    image: UNSPLASH('photo-1528825871115-3581a5387919'),
    requiresImage: true,
    uploadLabel: '上传参考图片',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的编辑效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 16,
    slug: 'banana-pro-t2i',
    title: '香蕉Pro文生图',
    featureKey: 'banana-pro-t2i',
    category: 'super_ai',
    image: UNSPLASH('photo-1558618666-fcd25c85cd64'),
    requiresImage: false,
    uploadLabel: '',
    uploadHint: '',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的图片效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 17,
    slug: 'banana-pro-dual',
    title: '香蕉Pro双图融合',
    featureKey: 'banana-pro-dual',
    category: 'super_ai',
    image: UNSPLASH('photo-1557683316-973673baf926'),
    requiresImage: true,
    uploadLabel: '上传目标图（第一张）',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述融合效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: true,
    dualImageLabel: '上传风格参考图（第二张）',
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 3,
    slug: 'atmosphere-render',
    title: '室内氛围渲染',
    featureKey: 'atmosphere-change',
    category: 'interior_ai',
    image: UNSPLASH('photo-1600607687939-ce8a6c25118c'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的氛围...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'target_atmosphere',
        label: '目标氛围',
        type: 'select',
        options: [
          { label: '清晨暖阳', value: '清晨暖阳' },
          { label: '午后柔光', value: '午后柔光' },
          { label: '黄昏金色', value: '黄昏金色' },
          { label: '夜晚灯光', value: '夜晚灯光' },
          { label: '阴天柔和', value: '阴天柔和' },
          { label: '月光冷色', value: '月光冷色' },
        ],
        defaultValue: '午后柔光',
      },
    ],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 4,
    slug: 'lighting-render',
    title: '光影渲染',
    featureKey: 'lighting-master',
    category: 'interior_ai',
    image: UNSPLASH('photo-1497366216548-37526070297c'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的光影效果...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'lighting_type',
        label: '光照类型',
        type: 'select',
        options: [
          { label: '自然光', value: 'natural' },
          { label: '人工光', value: 'artificial' },
          { label: '混合光', value: 'mixed' },
        ],
        defaultValue: 'mixed',
      },
    ],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 5,
    slug: 'multi-view',
    title: '室内多角度生图',
    featureKey: 'multi-view',
    category: 'interior_ai',
    image: UNSPLASH('photo-1507089947368-19c1da9775ae'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的视角...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'target_views',
        label: '目标视角',
        type: 'select',
        options: [
          { label: '左侧 45°', value: '左侧45度' },
          { label: '右侧 45°', value: '右侧45度' },
          { label: '正面', value: '正面' },
          { label: '俯视', value: '俯视' },
        ],
        defaultValue: '左侧45度',
      },
    ],
    costPerGeneration: 4,
    outputType: 'image',
  },
  {
    id: 6,
    slug: 'partial-replace',
    title: '室内局部替换',
    featureKey: 'partial-replace',
    category: 'interior_ai',
    image: UNSPLASH('photo-1493809842364-78817add7ffb'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想替换成什么，如"把沙发换成布艺沙发"...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: true,
    regionHint: '圈选需要替换的区域',
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 7,
    slug: 'material-modify',
    title: '局部材质修改',
    featureKey: 'local-material-change',
    category: 'interior_ai',
    image: UNSPLASH('photo-1519947486511-46149fa0a254'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP；可追加材质参考图',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的新材质，如"大理石纹理"...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: true,
    dualImageLabel: '上传参考材质图片（第二张，可选）',
    requiresSecondImage: false,
    hasRoomSelect: false,
    hasRegion: true,
    regionHint: '圈选需要修改材质的区域',
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 8,
    slug: 'style-transfer',
    title: '室内风格迁移',
    featureKey: 'style-transfer',
    category: 'interior_ai',
    image: UNSPLASH('photo-1513694203232-719a280e022f'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述其他风格要求...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'target_style',
        label: '目标风格',
        type: 'select',
        options: [
          { label: '现代简约', value: '现代简约' },
          { label: '北欧', value: '北欧' },
          { label: '新中式', value: '新中式' },
          { label: '侘寂', value: '侘寂' },
          { label: '法式', value: '法式' },
          { label: '工业风', value: '工业风' },
          { label: '日式', value: '日式' },
          { label: '美式', value: '美式' },
          { label: '轻奢', value: '轻奢' },
        ],
        defaultValue: '现代简约',
      },
      {
        key: 'preserve_level',
        label: '保留程度',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.1,
        defaultValue: 0.5,
      },
    ],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 9,
    slug: 'white-model',
    title: '白膜生图',
    featureKey: 'white-model-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1598928506311-c55ded91a20c'),
    uploadLabel: '上传白模截图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的装修风格和效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'space_type',
        label: '空间类型',
        type: 'select',
        options: [
          { label: '客厅', value: '客厅' },
          { label: '卧室', value: '卧室' },
          { label: '厨房', value: '厨房' },
          { label: '卫生间', value: '卫生间' },
          { label: '书房', value: '书房' },
          { label: '餐厅', value: '餐厅' },
          { label: '玄关', value: '玄关' },
        ],
        defaultValue: '客厅',
      },
    ],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 10,
    slug: 'rough-house',
    title: '毛坯房出图',
    featureKey: 'rough-house-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1517175510260-29a36371f845'),
    uploadLabel: '上传毛坯房照片',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的装修风格...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'design_style',
        label: '装修风格',
        type: 'select',
        options: [
          { label: '现代简约', value: '现代简约' },
          { label: '北欧', value: '北欧' },
          { label: '新中式', value: '新中式' },
          { label: '轻奢', value: '轻奢' },
          { label: '工业风', value: '工业风' },
        ],
        defaultValue: '现代简约',
      },
      {
        key: 'budget_level',
        label: '预算等级',
        type: 'select',
        options: [
          { label: '经济', value: '经济' },
          { label: '中等', value: '中等' },
          { label: '高端', value: '高端' },
        ],
        defaultValue: '中等',
      },
    ],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 11,
    slug: 'quality-enhance',
    title: '室内质感增强',
    featureKey: 'quality-enhance',
    category: 'interior_ai',
    image: UNSPLASH('photo-1493663284031-b7e3aefcae8e'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: false,
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'enhance_level',
        label: '增强等级',
        type: 'select',
        options: [
          { label: '轻微', value: '1' },
          { label: '标准', value: '2' },
          { label: '深度', value: '3' },
        ],
        defaultValue: '2',
      },
    ],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 12,
    slug: 'line-render',
    title: '线稿生图',
    featureKey: 'line-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1531835551805-16d864c8d311'),
    uploadLabel: '上传手绘线稿',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的渲染效果...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: true,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 2,
    outputType: 'image',
  },
  // --- P3 功能 ---
  {
    id: 20,
    slug: 'collage-render',
    title: '软装拼贴出图',
    featureKey: 'collage-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1618221195710-dd6b41eaea6e'),
    uploadLabel: '上传目标空间图（第一张）',
    uploadHint: '支持 JPG, PNG, WEBP；单图时为拼贴参考',
    hasPrompt: true,
    promptPlaceholder: '描述空间类型或风格要求，如"客厅"、"现代简约"...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: true,
    dualImageLabel: '上传拼贴参考图（第二张，可选）',
    requiresSecondImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'space_type',
        label: '空间类型',
        type: 'select',
        options: [
          { label: '客厅', value: '客厅' },
          { label: '卧室', value: '卧室' },
          { label: '餐厅', value: '餐厅' },
          { label: '书房', value: '书房' },
          { label: '厨房', value: '厨房' },
        ],
        defaultValue: '客厅',
      },
    ],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 21,
    slug: 'locked-material-render',
    title: '锁定材质出图',
    featureKey: 'locked-material-render',
    category: 'interior_ai',
    image: UNSPLASH('photo-1616486338812-3dadae4b4ace'),
    uploadLabel: '上传 3D 模型截图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '补充材质描述或增强要求...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 22,
    slug: 'material-replace',
    title: '材质替换',
    featureKey: 'material-replace',
    category: 'interior_ai',
    image: UNSPLASH('photo-1615873968393-ba2c7d279834'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述目标材质，如"大理石纹理"、"木纹地板"...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: true,
    regionHint: '圈选需要替换材质的区域',
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 23,
    slug: 'local-lighting',
    title: '局部开灯',
    featureKey: 'local-lighting',
    category: 'interior_ai',
    image: UNSPLASH('photo-1505693416388-ac5ce068fe85'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述灯光效果，如"暖光"、"冷白光"...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: true,
    regionHint: '圈选需要开灯的区域',
    customParams: [
      {
        key: 'light_type',
        label: '灯光类型',
        type: 'select',
        options: [
          { label: '暖光', value: 'warm' },
          { label: '冷光', value: 'cool' },
          { label: '彩色光', value: 'colored' },
        ],
        defaultValue: 'warm',
      },
      {
        key: 'brightness',
        label: '亮度',
        type: 'slider',
        min: 0.3,
        max: 1,
        step: 0.1,
        defaultValue: 0.7,
      },
    ],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 24,
    slug: 'color-floor-plan',
    title: '彩平图',
    featureKey: 'color-floor-plan',
    category: 'interior_ai',
    image: UNSPLASH('photo-1503387762-592deb58ef4e'),
    uploadLabel: '上传户型图或室内照片',
    uploadHint: '支持 JPG, PNG, WEBP（Beta）',
    hasPrompt: true,
    promptPlaceholder: '补充色彩或标注要求...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [
      {
        key: 'show_labels',
        label: '显示标注',
        type: 'toggle',
        defaultValue: true,
      },
    ],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 25,
    slug: 'floor-plan-layout',
    title: '平面布局方案',
    featureKey: 'floor-plan-layout',
    category: 'interior_ai',
    image: UNSPLASH('photo-1503387762-592deb58ef4e'),
    uploadLabel: '上传户型图',
    uploadHint: '支持 JPG, PNG, WEBP（Beta）',
    hasPrompt: true,
    promptPlaceholder: '描述家庭成员或功能需求...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 26,
    slug: 'material-channel',
    title: '材质通道图',
    featureKey: 'material-channel',
    category: 'interior_ai',
    image: UNSPLASH('photo-1616486338812-3dadae4b4ace'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP（Beta）',
    hasPrompt: false,
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 27,
    slug: 'furniture-list',
    title: '软装物料清单',
    featureKey: 'furniture-list',
    category: 'interior_ai',
    requiresImage: true,
    image: UNSPLASH('photo-1493809842364-78817add7ffb'),
    uploadLabel: '上传室内效果图',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '指定关注区域或物品类型（可选）...',
    hasResolution: false,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 1,
    outputType: 'text',
  },
  {
    id: 18,
    slug: 'style-mimic',
    title: '图片风格模仿',
    featureKey: 'style-mimic',
    category: 'toolbox',
    image: UNSPLASH('photo-1513694203232-719a280e022f'),
    requiresImage: true,
    uploadLabel: '上传目标图（第一张）',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: true,
    promptPlaceholder: '描述风格迁移效果...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: true,
    dualImageLabel: '上传风格参考图（第二张）',
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
  {
    id: 19,
    slug: 'toolbox-t2i',
    title: '工具箱文生图',
    featureKey: 'toolbox-t2i',
    category: 'toolbox',
    image: UNSPLASH('photo-1557683316-973673baf926'),
    requiresImage: false,
    uploadLabel: '',
    uploadHint: '',
    hasPrompt: true,
    promptPlaceholder: '描述你想要的图片...',
    hasResolution: true,
    hasAspectRatio: true,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 2,
    outputType: 'image',
  },
  {
    id: 13,
    slug: 'remove-watermark',
    title: '图片去水印',
    featureKey: 'remove-watermark',
    category: 'toolbox',
    image: UNSPLASH('photo-1501183638710-841dd1904471'),
    uploadLabel: '上传需要去水印的图片',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: false,
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 1,
    outputType: 'image',
  },
  {
    id: 14,
    slug: 'remove-bg',
    title: '图片去背景',
    featureKey: 'material-extract',
    category: 'toolbox',
    image: UNSPLASH('photo-1533090161767-918d7e44df63'),
    uploadLabel: '上传需要去背景的图片',
    uploadHint: '支持 JPG, PNG, WEBP',
    hasPrompt: false,
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: false,
    hasRoomSelect: false,
    hasRegion: false,
    customParams: [],
    costPerGeneration: 1,
    outputType: 'image',
  },
  {
    id: 15,
    slug: 'add-model',
    title: '场景加模特',
    featureKey: 'universal-edit',
    category: 'human',
    image: UNSPLASH('photo-1502005229766-31d3d2946c8e'),
    uploadLabel: '上传场景图片（第一张）',
    uploadHint: '支持 JPG, PNG, WEBP；可选上传模特参考图',
    hasPrompt: true,
    promptPlaceholder: '描述你想要添加的人物，如"一位穿白色连衣裙的女模特站在沙发旁"...',
    hasResolution: true,
    hasAspectRatio: false,
    hasDualImage: true,
    dualImageLabel: '上传模特参考图（第二张，可选）',
    requiresSecondImage: false,
    hasRoomSelect: false,
    hasRegion: true,
    regionHint: '圈选人物放置位置',
    customParams: [],
    costPerGeneration: 3,
    outputType: 'image',
  },
];

export const getToolBySlug = (slug: string): ToolConfig | undefined =>
  toolConfigs.find((t) => t.slug === slug);

export const getToolById = (id: number): ToolConfig | undefined =>
  toolConfigs.find((t) => t.id === id);

/** 分辨率 → 算力倍率；costPerGeneration 为 720p 基准 */
export const RESOLUTION_COST_MULTIPLIER: Record<string, number> = {
  '720p': 1,
  '1080p': 2,
  '2k': 3,
  '4k': 4,
};

export function getResolutionCost(baseCost: number, resolution: string): number {
  return baseCost * (RESOLUTION_COST_MULTIPLIER[resolution] ?? 2);
}

export const resolutions: ParamOption[] = [
  { label: '720p', value: '720p' },
  { label: '1080p', value: '1080p' },
  { label: '2k', value: '2k' },
  { label: '4k', value: '4k' },
];

export const getResolutionsByChannel = (
  tool: ToolConfig,
  engineType?: EngineTypeKey | null
): ParamOption[] => {
  if (!tool.hasResolution || tool.outputType === 'text') return [];

  const type = (engineType || '').toLowerCase();
  const isImageDriven = tool.requiresImage !== false || tool.hasDualImage;

  // Venice 的图生图链路高分档不稳定，编辑类仅开放 1080p；文生图保留 2K/4K。
  if (type === 'venice' && isImageDriven) {
    return resolutions.filter((r) => r.value === '1080p');
  }

  return resolutions;
};

export const aspectRatios: ParamOption[] = [
  { label: '默认', value: 'default' },
  { label: '1:1', value: '1:1' },
  { label: '4:3', value: '4:3' },
  { label: '3:4', value: '3:4' },
  { label: '16:9', value: '16:9' },
  { label: '9:16', value: '9:16' },
];
